---
# tasks file for ipsec-certs
#

- name: Install ipsec packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ ipsec_packages }}"

- name: Load SELinux policy
  include_tasks: selinux.yml

- name: Managing CA Certificates
  include_tasks: load_ca.yml

- name: Setup Certmonger
  include_tasks: invoke_certmonger.yml


